CREATE TABLE CATEGORIES (
    ID NUMBER,
    CONSTRAINT CATEGORY_PK PRIMARY KEY(ID),
    CATEGORY_NAME NVARCHAR2(50),
    DESCRIPTION CLOB,
    PICTURE NVARCHAR2(50)
);

CREATE TABLE CUSTOMERS (
    ID NUMBER,
    CONSTRAINT CUSTOMER_PK PRIMARY KEY(ID),
    COMPANY_NAME NVARCHAR2(50),
    CONTACT_NAME NVARCHAR2(50),
    CONTACT_TITLE NVARCHAR2(20),
    ADDRESS NVARCHAR2(50),
    CITY NVARCHAR2(20),
    REGION NVARCHAR2(20),
    POSTAL_CODE NVARCHAR2(10),
    COUNTRY NVARCHAR2(20),
    PHONE NVARCHAR2(50),
    FAX NVARCHAR2(50)
);

CREATE TABLE SUPPLIERS (
    ID NUMBER,
    CONSTRAINT SUPPLIER_PK PRIMARY KEY(ID),
    COMPANY_NAME NVARCHAR2(50),
    CONTACT_NAME NVARCHAR2(50),
    CONTACT_TITLE NVARCHAR2(20),
    ADDRESS NVARCHAR2(50),
    CITY NVARCHAR2(20),
    REGION NVARCHAR2(20),
    POSTAL_CODE NVARCHAR2(10),
    COUNTRY NVARCHAR2(20),
    PHONE NVARCHAR2(50),
    FAX NVARCHAR2(50),
    HOME_PAGE NVARCHAR2(50)
);

CREATE TABLE EMPLOYEES (
    ID NUMBER,
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY(ID),
    LAST_NAME NVARCHAR2(50),
    FIRST_NAME NVARCHAR2(50),
    TITLE NVARCHAR2(20),
    TITLE_OF_COURTESY NVARCHAR2(20),
    BIRTH_DATE TIMESTAMP,
    HIRE_DATE TIMESTAMP,
    ADDRESS NVARCHAR2(50),
    CITY NVARCHAR2(20),
    REGION NVARCHAR2(20),
    POSTAL_CODE NVARCHAR2(10),
    COUNTRY NVARCHAR2(20),
    HOME_PHONE NVARCHAR2(50),
    EXTENSION NVARCHAR2(20),
    PHOTO NVARCHAR2(50),
    NOTES CLOB,
    REPORTS_TO NVARCHAR2(50)
);

CREATE TABLE SHIPPERS (
    ID NUMBER,
    CONSTRAINT SHIPPER_PK PRIMARY KEY(ID),
    COMPANY_NAME NVARCHAR2(50),
    PHONE NVARCHAR2(20)
);

CREATE TABLE PRODUCTS (
    ID NUMBER,
    CONSTRAINT PRODUCT_PK PRIMARY KEY(ID),
    PRODUCT_NAME NVARCHAR2(50),
    SUPPLIER_ID NUMBER,
    CONSTRAINT SUPPLIER_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(ID),
    CATEGORY_ID NUMBER,
    CONSTRAINT CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID),
    QUANTITY_PER_UNIT NUMBER,
    UNIT_PRICE NUMBER(*, 2),
    UNITS_IN_STOCK NUMBER,
    UNITS_ON_ORDER NUMBER,
    RECORDER_LEVEL NUMBER,
    DISCONTINUED NUMBER(1)
);

CREATE TABLE ORDERS (
    ID NUMBER,
    CONSTRAINT ORDER_PK PRIMARY KEY(ID),
    CUSTOMER_ID NUMBER,
    CONSTRAINT CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    EMPLOYEE_ID NUMBER,
    CONSTRAINT EMPLOYEE_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID),
    ORDER_DATE TIMESTAMP,
    REQUIRED_DATE TIMESTAMP,
    SHIPPED_DATE TIMESTAMP,
    SHIP_VIA NVARCHAR2(50),
    FREIGHT NVARCHAR2(50),
    SHIP_NAME NVARCHAR2(50),
    SHIP_ADDRESS NVARCHAR2(50),
    SHIP_CITY NVARCHAR2(20),
    SHIP_REGION NVARCHAR2(20),
    SHIP_POSTAL_CODE NVARCHAR2(10),
    SHIP_COUNTRY NVARCHAR2(50)
);


CREATE TABLE ORDER_DETAILS (
    ID NUMBER,
    CONSTRAINT ORDER_DETAILS_PK PRIMARY KEY(ID),
    ORDER_ID NUMBER,
    CONSTRAINT ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
    PRODUCT_ID NUMBER,
    CONSTRAINT PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
    UNIT_PRICE NUMBER(*, 2),
    QUANTITY NUMBER,
    DISCOUNT NUMBER(*, 2)
);