SELECT DIRECTOR, COUNT(*) FROM MOVIE
GROUP BY DIRECTOR;

SELECT DIRECTOR, SUM(DOMESTIC_SALES), SUM(INTERNATIONAL_SALES) FROM MOVIE
INNER JOIN MOVIE_STAT ON MOVIE_STAT.MOVIE_ID = MOVIE.ID
GROUP BY DIRECTOR;

SELECT DIRECTOR, SUM(DOMESTIC_SALES), SUM(INTERNATIONAL_SALES) FROM MOVIE, MOVIE_STAT
WHERE MOVIE_STAT.MOVIE_ID = MOVIE.ID
GROUP BY DIRECTOR;